export default [
  'What are you working on?',
  'How did you start working on this?',
  'Have you run beta users through this yet? What did you learn from them? What went wrong?',
  'How many users did/do you have?',
  'Who is your customer/user?',
  'Is there anything that they told you that changed what you were doing?',
  'What is your next step?',
  'Are you programmers?',
  'People lie. How do you know this customer actually wants what you are selling?',
  'What do you think will be the most popular part about this?',
  'Why will people continue to use your product?',
  'What does this thing you are replacing do?',
  'What do you actually do?',
  'How much does the existing solution cost?',
  'How did you get those customers?',
  'Why has no one done this before?',
  'How are you going to get the existing customers to adopt your thing?',
  'How far along are you?',
  'How many events have you done with your first customers?',
  'How much do you make per customer?',
  'How much will you be able to make?',
  'Will your team stick at this?',
  'Who would you hire or how would you add to your team?',
  'How did your team meet?',
  'Who in your team does what?',
  'Who is "the boss"?',
  'Why will you succeed over others?',
  'What do you understand that others don\'t?',
  'What have you learned so far from working on it? ',
  'In what ways are you resourceful?',
  'Would you relocate to Silicon Valley?',
  'What’s the biggest mistake you have made?',
  'What competition do you fear most?',
  'Who might become competitors?',
  'Who are your competitors?',
  'What do they use to solve that problem right now?',
  'What, exactly, makes you different from existing options? ',
  'What is your burn rate?',
  'How long can you go before funding?',
  'Have you raised funding?',
  'How much money could you make per year?',
  'How will you make money?',
  'How much does customer acquisition cost?',
  'How are you meeting customers?',
  'How many users are paying?',
  'What will you do if we don\'t fund you? ',
  'Who is your user?',
  'What problem are you helping them with?',
  'Why is this a problem for them?',
  'What do they like about this solution?',
  'What do they not like about this solution?',
  'How do you know customers need what you’re making?',
  'What do they wish that solution could do for them?',
  'How is your solution better?',
  'Why would they switch to your solution?',
  'What do you know about these users that no one else knows?',
  'How many of these users are there?',
  'How many do you have now?',
  'How did you get them?',
  'What’s the conversion rate?',
  'How will you get more?',
  'How many more will you have in 3 months?',
  'What do these users currently pay to have this problem solved?',
  'Would they be willing to pay more for something better?',
  'Why are these users good users to try to solve problems for?',
  'What other kinds of users could you go after once you get all these users using your product?',
  'What makes new users try you?',
  'Why did you pick this idea to work on?',
  'Why do the reluctant users hold back?',
  'What problems/hurdles are you anticipating?',
  'How will you overcome them?',
  'What are the top things users want?',
  'What is your user growth rate?',
  'What has surprised you about user behaviour?',
  'What are the key things about your field that outsiders don\'t understand? What do you understand that others don\'t?',
  'How are you understanding customer needs?',
  'How will customers and/or users find out about you?',
  'What is your distribution strategy?',
  'What’s the funniest thing that has happened to you?',
  'Tell us something surprising you have done.',
  'What’s the worst thing that has happened?',
  'What’s an impressive thing you have done?',
  'What systems have you hacked?',
  'Where is the rocket science here?',
  'What is the next step with the product evolution?',
  'What obstacles will you face and how will you overcome them?',
  'How does your product work in more detail?',
  'Six months from now, what’s going to be your biggest problem?',
  'What’s new about what you make?',
  'Why isn’t someone already doing this?',
  'How is your product different?',
  'Are you open to changing your idea?'
];
